version: "3.8"
services:
  postgres:
    container_name: lettfaktura
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

volumes:
  lettfaktura:
